import {
  Baby,
  Briefcase,
  BookOpen,
  Car,
  Coffee,
  CreditCard,
  Dumbbell,
  Gift,
  GraduationCap,
  Home,
  type LucideIcon,
  PawPrint,
  PiggyBank,
  Plane,
  Popcorn,
  Repeat,
  Shapes,
  Shirt,
  ShoppingCart,
  Stethoscope,
  TrendingUp,
  Utensils,
  Wrench,
} from 'lucide-react';

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  'trending-up': TrendingUp,
  utensils: Utensils,
  car: Car,
  home: Home,
  popcorn: Popcorn,
  stethoscope: Stethoscope,
  repeat: Repeat,
  shapes: Shapes,
  'shopping-cart': ShoppingCart,
  gift: Gift,
  plane: Plane,
  'graduation-cap': GraduationCap,
  briefcase: Briefcase,
  'piggy-bank': PiggyBank,
  'credit-card': CreditCard,
  'book-open': BookOpen,
  dumbbell: Dumbbell,
  baby: Baby,
  'paw-print': PawPrint,
  wrench: Wrench,
  shirt: Shirt,
  coffee: Coffee,
};

export function getCategoryIcon(iconName: string): LucideIcon {
  return CATEGORY_ICONS[iconName] ?? Shapes;
}
